# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class List_Cliente(object):
    def setupUi(self, List_Cliente):
        if not List_Cliente.objectName():
            List_Cliente.setObjectName(u"List_Cliente")
        List_Cliente.resize(930, 650)
        font = QFont()
        font.setFamily(u"LEMON MILK Bold")
        font.setBold(True)
        font.setWeight(75)
        List_Cliente.setFont(font)
        List_Cliente.setAutoFillBackground(False)
        List_Cliente.setStyleSheet(u"background-color: rgb(30, 30, 30);\n"
"\n"
"")
        self.frame_imagenes = QFrame(List_Cliente)
        self.frame_imagenes.setObjectName(u"frame_imagenes")
        self.frame_imagenes.setGeometry(QRect(10, 10, 901, 81))
        self.frame_imagenes.setFrameShape(QFrame.StyledPanel)
        self.frame_imagenes.setFrameShadow(QFrame.Raised)
        self.label_BD_Clientes = QLabel(self.frame_imagenes)
        self.label_BD_Clientes.setObjectName(u"label_BD_Clientes")
        self.label_BD_Clientes.setGeometry(QRect(610, 10, 271, 51))
        font1 = QFont()
        font1.setFamily(u"LEMON MILK Bold")
        font1.setPointSize(24)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_BD_Clientes.setFont(font1)
        self.label_BD_Clientes.setLayoutDirection(Qt.LeftToRight)
        self.label_BD_Clientes.setAutoFillBackground(False)
        self.label_BD_Clientes.setStyleSheet(u"background-color: rgb(30, 30,30);\n"
"color: rgb(124, 255, 155);")
        self.pushButton = QPushButton(self.frame_imagenes)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(40, 10, 351, 71))
        icon = QIcon()
        icon.addFile(u"./assets/images/logo-momentum.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QSize(300, 300))
        self.frame = QFrame(List_Cliente)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 90, 911, 221))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.add_cliente = QPushButton(self.frame)
        self.add_cliente.setObjectName(u"add_cliente")
        self.add_cliente.setGeometry(QRect(60, 10, 121, 111))
        self.add_cliente.setCursor(QCursor(Qt.PointingHandCursor))
        self.add_cliente.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        icon1 = QIcon()
        icon1.addFile(u"./assets/icons/2150373-social-media/png/001-add user.png", QSize(), QIcon.Normal, QIcon.Off)
        self.add_cliente.setIcon(icon1)
        self.add_cliente.setIconSize(QSize(100, 100))
        self.add_cliente.setFlat(True)
        self.add_pdf = QPushButton(self.frame)
        self.add_pdf.setObjectName(u"add_pdf")
        self.add_pdf.setGeometry(QRect(230, 10, 121, 111))
        self.add_pdf.setCursor(QCursor(Qt.PointingHandCursor))
        self.add_pdf.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        icon2 = QIcon()
        icon2.addFile(u"./assets/icons/2150373-social-media/png/035-profile.png", QSize(), QIcon.Normal, QIcon.Off)
        self.add_pdf.setIcon(icon2)
        self.add_pdf.setIconSize(QSize(100, 100))
        self.add_pdf.setFlat(True)
        self.add_cotizacion = QPushButton(self.frame)
        self.add_cotizacion.setObjectName(u"add_cotizacion")
        self.add_cotizacion.setGeometry(QRect(400, 10, 121, 111))
        self.add_cotizacion.setCursor(QCursor(Qt.PointingHandCursor))
        self.add_cotizacion.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        icon3 = QIcon()
        icon3.addFile(u"./assets/icons/2150373-social-media/png/031-online shop.png", QSize(), QIcon.Normal, QIcon.Off)
        self.add_cotizacion.setIcon(icon3)
        self.add_cotizacion.setIconSize(QSize(100, 100))
        self.add_cotizacion.setFlat(True)
        self.edit_cliente = QPushButton(self.frame)
        self.edit_cliente.setObjectName(u"edit_cliente")
        self.edit_cliente.setGeometry(QRect(560, 10, 121, 111))
        self.edit_cliente.setCursor(QCursor(Qt.PointingHandCursor))
        self.edit_cliente.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        icon4 = QIcon()
        icon4.addFile(u"./assets/icons/2150373-social-media/png/046-user-modify.png", QSize(), QIcon.Normal, QIcon.Off)
        self.edit_cliente.setIcon(icon4)
        self.edit_cliente.setIconSize(QSize(100, 100))
        self.edit_cliente.setFlat(True)
        self.spr_cliente = QPushButton(self.frame)
        self.spr_cliente.setObjectName(u"spr_cliente")
        self.spr_cliente.setGeometry(QRect(750, 10, 121, 111))
        self.spr_cliente.setCursor(QCursor(Qt.PointingHandCursor))
        self.spr_cliente.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        icon5 = QIcon()
        icon5.addFile(u"./assets/icons/2150373-social-media/png/037-remove user.png", QSize(), QIcon.Normal, QIcon.Off)
        self.spr_cliente.setIcon(icon5)
        self.spr_cliente.setIconSize(QSize(100, 100))
        self.spr_cliente.setFlat(True)
        self.add_user = QLabel(self.frame)
        self.add_user.setObjectName(u"add_user")
        self.add_user.setGeometry(QRect(50, 120, 121, 41))
        font2 = QFont()
        font2.setFamily(u"8514oem")
        font2.setPointSize(8)
        font2.setBold(False)
        font2.setWeight(50)
        self.add_user.setFont(font2)
        self.add_user.setStyleSheet(u"color: rgb(100, 252, 196);\n"
"")
        self.add_user.setAlignment(Qt.AlignCenter)
        self.add_user.setWordWrap(True)
        self.pdf = QLabel(self.frame)
        self.pdf.setObjectName(u"pdf")
        self.pdf.setGeometry(QRect(220, 130, 141, 16))
        self.pdf.setFont(font2)
        self.pdf.setStyleSheet(u"color: rgb(76, 108, 255);\n"
"")
        self.pdf.setAlignment(Qt.AlignCenter)
        self.cotizacion = QLabel(self.frame)
        self.cotizacion.setObjectName(u"cotizacion")
        self.cotizacion.setGeometry(QRect(400, 120, 111, 41))
        self.cotizacion.setFont(font2)
        self.cotizacion.setStyleSheet(u"color: rgb(255, 76, 76);\n"
"")
        self.cotizacion.setAlignment(Qt.AlignCenter)
        self.cotizacion.setWordWrap(True)
        self.cotizacion_2 = QLabel(self.frame)
        self.cotizacion_2.setObjectName(u"cotizacion_2")
        self.cotizacion_2.setGeometry(QRect(570, 120, 111, 41))
        self.cotizacion_2.setFont(font2)
        self.cotizacion_2.setStyleSheet(u"color: rgb(242, 255, 76);\n"
"")
        self.cotizacion_2.setAlignment(Qt.AlignCenter)
        self.cotizacion_2.setWordWrap(True)
        self.cotizacion_3 = QLabel(self.frame)
        self.cotizacion_3.setObjectName(u"cotizacion_3")
        self.cotizacion_3.setGeometry(QRect(750, 120, 111, 41))
        self.cotizacion_3.setFont(font2)
        self.cotizacion_3.setStyleSheet(u"color: rgb(255, 76, 76);\n"
"")
        self.cotizacion_3.setAlignment(Qt.AlignCenter)
        self.cotizacion_3.setWordWrap(True)
        self.busqueda = QTextEdit(self.frame)
        self.busqueda.setObjectName(u"busqueda")
        self.busqueda.setGeometry(QRect(300, 190, 381, 31))
        font3 = QFont()
        font3.setFamily(u"8514oem")
        font3.setPointSize(8)
        self.busqueda.setFont(font3)
        self.busqueda.setStyleSheet(u"background-color: rgb(86, 86, 86);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);")
        self.Filtrar = QComboBox(self.frame)
        self.Filtrar.addItem("")
        self.Filtrar.addItem("")
        self.Filtrar.addItem("")
        self.Filtrar.setObjectName(u"Filtrar")
        self.Filtrar.setGeometry(QRect(160, 190, 131, 31))
        self.Filtrar.setFont(font2)
        self.Filtrar.setStyleSheet(u"background-color: rgb(86, 86, 86);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);")
        self.filtrar = QLabel(self.frame)
        self.filtrar.setObjectName(u"filtrar")
        self.filtrar.setGeometry(QRect(20, 190, 121, 31))
        font4 = QFont()
        font4.setFamily(u"8514oem")
        font4.setPointSize(8)
        font4.setBold(True)
        font4.setWeight(75)
        self.filtrar.setFont(font4)
        self.filtrar.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.filtrar.setAlignment(Qt.AlignCenter)
        self.filtrar.setWordWrap(True)
        self.buscar = QPushButton(self.frame)
        self.buscar.setObjectName(u"buscar")
        self.buscar.setGeometry(QRect(690, 190, 93, 31))
        font5 = QFont()
        font5.setFamily(u"8514oem")
        self.buscar.setFont(font5)
        self.buscar.setCursor(QCursor(Qt.PointingHandCursor))
        self.buscar.setStyleSheet(u"background-color: rgb(86, 86, 86);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);\n"
"box-shadow: 2px 2px 5px ;\n"
"")
        icon6 = QIcon()
        icon6.addFile(u"./assets/icons/2150373-social-media/png/039-search.png", QSize(), QIcon.Normal, QIcon.Off)
        self.buscar.setIcon(icon6)
        self.buscar.setCheckable(False)
        self.buscar.setAutoDefault(False)
        self.buscar.setFlat(False)
        self.actualizar = QPushButton(self.frame)
        self.actualizar.setObjectName(u"actualizar")
        self.actualizar.setGeometry(QRect(790, 190, 121, 31))
        self.actualizar.setFont(font5)
        self.actualizar.setCursor(QCursor(Qt.PointingHandCursor))
        self.actualizar.setStyleSheet(u"background-color: rgb(86, 86, 86);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);")
        icon7 = QIcon()
        icon7.addFile(u"./assets/icons/2150373-social-media/png/updated.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actualizar.setIcon(icon7)
        self.abajo = QFrame(List_Cliente)
        self.abajo.setObjectName(u"abajo")
        self.abajo.setGeometry(QRect(10, 590, 901, 31))
        self.abajo.setFrameShape(QFrame.StyledPanel)
        self.abajo.setFrameShadow(QFrame.Raised)
        self.numero_clientes = QLabel(self.abajo)
        self.numero_clientes.setObjectName(u"numero_clientes")
        self.numero_clientes.setGeometry(QRect(10, 0, 251, 31))
        self.numero_clientes.setFont(font4)
        self.numero_clientes.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.numero_clientes.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.numero_clientes.setWordWrap(False)
        self.usuarios_n = QLabel(self.abajo)
        self.usuarios_n.setObjectName(u"usuarios_n")
        self.usuarios_n.setGeometry(QRect(250, 0, 291, 31))
        font6 = QFont()
        font6.setFamily(u"LEMON MILK")
        font6.setPointSize(11)
        font6.setBold(True)
        font6.setWeight(75)
        self.usuarios_n.setFont(font6)
        self.usuarios_n.setStyleSheet(u"background-color: rgb(86, 86, 86);\n"
"border-radius: 5px;\n"
"color: rgb(255, 255, 255);")
        self.usuarios_n.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.usuarios_n.setWordWrap(False)
        self.table_clientes = QTableWidget(List_Cliente)
        self.table_clientes.setObjectName(u"table_clientes")
        self.table_clientes.setGeometry(QRect(10, 320, 911, 261))
        self.table_clientes.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"color: rgb(16, 16, 16);")

        self.retranslateUi(List_Cliente)

        self.buscar.setDefault(False)


        QMetaObject.connectSlotsByName(List_Cliente)
    # setupUi

    def retranslateUi(self, List_Cliente):
        List_Cliente.setWindowTitle(QCoreApplication.translate("List_Cliente", u"BD Momentum", None))
        self.label_BD_Clientes.setText(QCoreApplication.translate("List_Cliente", u"BD CLIENTES", None))
        self.pushButton.setText("")
        self.add_cliente.setText("")
        self.add_pdf.setText("")
        self.add_cotizacion.setText("")
        self.edit_cliente.setText("")
        self.spr_cliente.setText("")
        self.add_user.setText(QCoreApplication.translate("List_Cliente", u"Agregar Usuario", None))
        self.pdf.setText(QCoreApplication.translate("List_Cliente", u"Generar PDF", None))
        self.cotizacion.setText(QCoreApplication.translate("List_Cliente", u"Generar Cotizacion    ", None))
        self.cotizacion_2.setText(QCoreApplication.translate("List_Cliente", u"Editar Usuario", None))
        self.cotizacion_3.setText(QCoreApplication.translate("List_Cliente", u"Eliminar Usuario", None))
        self.busqueda.setMarkdown("")
        self.busqueda.setHtml(QCoreApplication.translate("List_Cliente", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'8514oem'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:6px; margin-bottom:6px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.Filtrar.setItemText(0, QCoreApplication.translate("List_Cliente", u"Nombre", None))
        self.Filtrar.setItemText(1, QCoreApplication.translate("List_Cliente", u"C\u00e9dula", None))
        self.Filtrar.setItemText(2, QCoreApplication.translate("List_Cliente", u"Fecha", None))

        self.filtrar.setText(QCoreApplication.translate("List_Cliente", u"FILTRAR", None))
        self.buscar.setText(QCoreApplication.translate("List_Cliente", u"Buscar", None))
        self.actualizar.setText(QCoreApplication.translate("List_Cliente", u"Actualizar", None))
        self.numero_clientes.setText(QCoreApplication.translate("List_Cliente", u"Usuarios Registrados:", None))
        self.usuarios_n.setText("")
    # retranslateUi

